package local

import (
	"context"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
)

// config.go — Spec S12.2 llama-swap config generation (brief R10). The config
// is GENERATED from the manifest + ⚙, never hand-written. Placement is by GPU
// UUID (never index — indices renumber on eGPU attach, S12.2/S12.7); the UUID
// is live-read via nvidia-smi (GPUUUIDs, the ONE nvidia-smi read in this
// packet — R23: no periodic GPU polling anywhere, monitoring never defeats
// RTD3). The generator emits ONLY GPU-seated SERVABLE seats into a `pool12`
// swap group (members hold the pool exclusively — loading one unloads the
// others, S12.2); the `resident` group is EMPTY (S12.8 revision: no
// always-resident slot, RTD3 mutual exclusion); `pool24` is NOT configured
// (S12.11 dormant); no embedder member (post-gate). Non-servable CPU seats
// (DeBERTa NLI, Flan-T5) are recorded honestly in the manifest and NEVER faked
// into config (R10).
//
// The llama-swap YAML schema is live-verified at the pinned release (v241):
// models are keyed by id with cmd/ttl/env/unloadTimeout; groups carry
// swap/exclusive/persistent/members (swap:true ⇒ one member at a time). The
// generator is asserted against this schema by the conformance suite (R26);
// the schema was probed from the pinned build's docs + example config, never
// assumed.
//
// Power/residency posture (S12.8; R23): this generated config carries NO
// residency slot (the resident group is empty), so `nvidia-persistenced` in
// UVM persistence mode is NEVER run by anything Sinet generates — it would
// disable RTD3 deep GPU sleep outright (S12.8). Nothing here or in the
// generated unit starts it (trivially satisfied). Background-inference clock
// caps (`-lgc`) need root and are an OPERATOR/hardening flag, never emitted or
// applied here.

// ConfigParams are the structural inputs to config generation (R10). The
// paths/endpoints are structural config (composition-root passthrough,
// gate-flagged under the settings-tab directive — §8 reading 7), the TTLs are
// ⚙, and the GPU UUID is live-read.
type ConfigParams struct {
	// ModelCacheDir is the shared read-only model-cache root (Spec S12.1
	// feature 4.1) — a structural-config root, operator-relocatable.
	ModelCacheDir string
	// GPUUUIDs are the live-read GPU UUIDs (GPUUUIDs()); index 0 is the
	// internal 12 GB GPU hosting pool12. Never indices (R10).
	GPUUUIDs []string
	// LlamaServer is the path to the llama-server backend binary (structural
	// config; the R3-resolved user-level build).
	LlamaServer string
	// TTLFastS / TTLWorkhorseS are ⚙ local.ttl.fast_s / local.ttl.workhorse_s.
	TTLFastS      int64
	TTLWorkhorseS int64
	// UnloadGraceS is ⚙ local.unload.term_grace_s, consumed here as the
	// per-model llama-swap `unloadTimeout` (the R10-comment optional
	// consumption — the live schema exposes the knob).
	UnloadGraceS int64
}

// GenerateConfig renders the llama-swap YAML from the manifest + params (R10).
// It is a pure function (the shell reads the UUID + ⚙ and passes them; tests
// inject a fixed UUID). A missing GPU UUID is a loud error — placement is by
// UUID and there is no honest index fallback (R10).
func GenerateConfig(p ConfigParams) (string, error) {
	if len(p.GPUUUIDs) == 0 {
		return "", fmt.Errorf("local: config generation needs at least one GPU UUID (live-read via nvidia-smi; placement is by UUID, never index — S12.2)")
	}
	if p.LlamaServer == "" {
		return "", fmt.Errorf("local: config generation needs the llama-server binary path (structural config)")
	}
	if p.ModelCacheDir == "" {
		return "", fmt.Errorf("local: config generation needs the model-cache dir (structural config)")
	}
	poolUUID := p.GPUUUIDs[0]

	var members []string
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by internal/local (Spec S12.2; brief R10). Do not hand-edit;\n")
	fmt.Fprintf(&b, "# regenerate from the manifest + ⚙. llama-swap pin %s, llama.cpp pin %s.\n", LlamaSwapPin, LlamaCppPin)
	fmt.Fprintf(&b, "# Placement by GPU UUID (never index); pool12 swap group (one member at a\n")
	fmt.Fprintf(&b, "# time); resident group EMPTY (S12.8 — no always-resident slot); pool24\n")
	fmt.Fprintf(&b, "# NOT configured (S12.11 dormant); no embedder member (G2 Def.8 post-gate).\n\n")

	b.WriteString("models:\n")
	for _, s := range Manifest() {
		if !s.GPUSeated || !s.Servable {
			// CPU/non-servable/post-gate seats are never faked into config
			// (R10); they live in the manifest with their honest Servable
			// note (DeBERTa NLI, Flan-T5, the post-gate embedder).
			continue
		}
		if len(s.Files) == 0 {
			continue
		}
		modelPath := filepath.Join(p.ModelCacheDir, s.Files[0].Name)
		ttl := p.TTLWorkhorseS
		if s.Seat == "fast" {
			ttl = p.TTLFastS // fast/CPU-class seat TTL (R10)
		}
		// Emit the BOUNDED serving context (drain F9), never the model's full
		// context — the full context would OOM on the 12 GB pool with fp16 KV.
		ctx := s.ServingContext
		if ctx == 0 {
			ctx = s.ContextLen
		}
		fmt.Fprintf(&b, "  %q:\n", s.Model)
		// --n-gpu-layers 999 fully offloads the pool12 seat to the GPU (its
		// CUDA_VISIBLE_DEVICES device); --ctx-size sets the bounded serving
		// context; KV cache stays fp16 (the default — the quant policy: KV
		// cache is never quantized, S12.3); --jinja applies the model's chat
		// template for /v1/chat/completions.
		fmt.Fprintf(&b, "    cmd: %q\n", fmt.Sprintf("%s --port ${PORT} --model %s --ctx-size %d --n-gpu-layers 999 --jinja", p.LlamaServer, modelPath, ctx))
		fmt.Fprintf(&b, "    ttl: %d\n", ttl)
		fmt.Fprintf(&b, "    unloadTimeout: %d\n", p.UnloadGraceS)
		// Per-model GPU placement by UUID (R10; S12.2 §4.1/§4.4).
		fmt.Fprintf(&b, "    env:\n      - %q\n", "CUDA_VISIBLE_DEVICES="+poolUUID)
		members = append(members, s.Model)
	}

	b.WriteString("\ngroups:\n")
	b.WriteString("  # pool12: the 12 GB internal GPU. swap:true ⇒ members hold the pool\n")
	b.WriteString("  # exclusively — loading one unloads the others (S12.2). exclusive:false\n")
	b.WriteString("  # (pool24 is dormant, S12.11); persistent:false (TTL-warm residency only,\n")
	b.WriteString("  # S12.8 — nothing pinned resident).\n")
	b.WriteString("  \"pool12\":\n")
	b.WriteString("    swap: true\n")
	b.WriteString("    exclusive: false\n")
	b.WriteString("    persistent: false\n")
	b.WriteString("    members:\n")
	for _, m := range members {
		fmt.Fprintf(&b, "      - %q\n", m)
	}
	// resident: MATERIALIZED as an actual empty group (drain F10 — verified
	// live that llama-swap v241 accepts it). Deliberately EMPTY (S12.8 revision
	// — an always-resident multi-GB model and deep GPU sleep (RTD3) are
	// mutually exclusive; every registry duty is event-driven, none
	// latency-critical below ~10 s). The operator may pin the fast tier at
	// runtime (an operator verb). pool24 (eGPU) is NOT configured until
	// enrollment (S12.11).
	b.WriteString("  \"resident\":\n")
	b.WriteString("    persistent: true\n")
	b.WriteString("    swap: false\n")
	b.WriteString("    members: []\n")

	return b.String(), nil
}

// GPUUUIDs live-reads the GPU UUIDs via nvidia-smi — the ONE nvidia-smi read
// in this packet, one-shot at config generation (R23: no periodic GPU polling;
// monitoring never defeats RTD3, S12.8). Placement is by UUID, never index
// (S12.2). A missing nvidia-smi or GPU returns an empty slice + error — the
// stack is not configurable (the caller degrades or flags).
func GPUUUIDs(ctx context.Context) ([]string, error) {
	out, err := exec.CommandContext(ctx, "nvidia-smi", "--query-gpu=uuid", "--format=csv,noheader").Output()
	if err != nil {
		return nil, fmt.Errorf("local: nvidia-smi UUID enumeration: %w", err)
	}
	var uuids []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if u := strings.TrimSpace(line); u != "" {
			uuids = append(uuids, u)
		}
	}
	if len(uuids) == 0 {
		return nil, fmt.Errorf("local: nvidia-smi returned no GPU UUIDs")
	}
	return uuids, nil
}
