package api_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/dariannixda-eng/Sinet-Agentic-Control-Hub/internal/api"
)

// webfixtures_test.go writes the fixtures the WEB suite consumes that are not
// the body of any GET.
//
// The golden-fixture mechanism §42 landed ties a Go handler's output to a
// vitest double so a rename fails the Go suite in the same commit. Two facts
// this packet has to tie across the language boundary are not served bodies at
// all, and they get the same treatment for the same reason:
//
//  1. the deep-link ENCODING a push `navigate` field carries, which the SPA's
//     own router has to resolve back to the exact card id (B6-9 rubric 8); and
//  2. the AUTHED ROUTE TABLE, so the S15.12 "the SPA consumes every API" check
//     is a comparison between two independently-produced lists rather than a
//     list compared to itself (B6-9 OQ11 / R17).
//
// Both are GENERATED FROM THE PRODUCTION CODE — the composer the notifier uses
// and the mux's own registered patterns — never hand-listed. A hand-listed
// inventory is the tautology B6-8 shipped once and is exactly what this
// mechanism exists to avoid.

// navigateFixture is the cross-language deep-link tie.
type navigateFixture struct {
	// Note explains to a reader of the committed file what it is for.
	Note  string         `json:"note"`
	Cases []navigateCase `json:"cases"`
}

type navigateCase struct {
	// CardID is the routable ApprovalItem id, verbatim.
	CardID string `json:"card_id"`
	// Path is what the SERVER composes into the push payload's `navigate`
	// field, after the subscription's own origin.
	Path string `json:"path"`
}

// navigateCardIDs are the id shapes a real inbox serves, including the three
// characters App.tsx names as the reason the encode/decode round trip exists:
// ':' in every `<kind>:<native-id>` composite, '#' from a fork's dispatch id,
// and the unit separator. The last few are shapes that would silently diverge
// between JavaScript's encodeURIComponent and Go's url.PathEscape.
var navigateCardIDs = []string{
	"ask:ask-verify-0001",
	"effect:e-9f2c1b4a-77de-4e21-9a3b-0c5d6e7f8a90",
	"watchdog_flag:r-ship.g2:watchdog.loop",
	"memory_conflict:41",
	"effect:e-rotate#g2",
	"ask:r-1.g2\x1fslot",
	"ask:a-_.!~*'()",
	"kind:a/b?c&d=e+f g",
	"ask:café",
	"ask:100%",
}

// TestNavigateDeepLinkFixture writes (or compares) the tie. The web half
// round-trips every `path` through the router's own matchRoute and asserts it
// resolves to `inbox-item` carrying the EXACT `card_id` back — so a change to
// either language's encoder fails on the other side's suite.
func TestNavigateDeepLinkFixture(t *testing.T) {
	fx := navigateFixture{
		Note: "Generated by internal/api (TestNavigateDeepLinkFixture). `path` is what the " +
			"S15.11 notifier composes into a push payload's `navigate` field, after the subscription's own " +
			"recorded origin. The web suite round-trips each one through matchRoute and requires the exact " +
			"`card_id` back: a tapped notification has to land on the card it names, and Go's url.PathEscape " +
			"is NOT the same rule as JavaScript's encodeURIComponent.",
	}
	for _, id := range navigateCardIDs {
		fx.Cases = append(fx.Cases, navigateCase{CardID: id, Path: api.NavigatePathForTest(id)})
	}
	raw, err := json.Marshal(fx)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	compareOrWriteFixture(t, "push-navigate", canonicalJSON(t, raw))
}

// compareOrWriteFixture is the §42 compare-only discipline applied to a
// generated body: it writes only under SINET_WRITE_API_FIXTURES, so `go test`
// never writes outside t.TempDir() on any run CI can make.
func compareOrWriteFixture(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join(fixtureDir, name+".json")
	if os.Getenv(fixtureWriteEnv) != "" {
		if err := os.MkdirAll(fixtureDir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", fixtureDir, err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v\n\nRegenerate with:\n  %s=1 go test ./internal/api -run TestNavigateDeepLinkFixture",
			path, err, fixtureWriteEnv)
	}
	if string(got) != string(want) {
		t.Errorf("%s drifted.\n\nThe web suite is built against the committed file, so this is a CONTRACT "+
			"change, not a test failure to silence. Review the diff, then regenerate with:\n  %s=1 go test ./internal/api\n\n"+
			"generated:\n%s\ncommitted:\n%s", path, fixtureWriteEnv, got, want)
	}
}

// muxNotFound is http.ServeMux's own unrouted-path body, verbatim. It is what
// tells a ROUTED handler's 404 apart from a path the mux never knew.
const muxNotFound = "404 page not found\n"

// routeInventory is the S15.12 completeness check's Go-side ground truth.
type routeInventory struct {
	Note   string      `json:"note"`
	Routes []api.Route `json:"routes"`
}

// TestRouteInventoryFixture writes the authed route table for the web suite's
// "the SPA consumes every API" check (S19.5; B6-9 R17).
//
// THE LIST IS PRODUCED BY THE REGISTRATION CALLS THEMSELVES — `Handler()`
// records each pattern as it registers it — so it cannot drift from what the
// mux serves and it is not a list somebody maintains. That is the whole point:
// B6-8 shipped an inventory table checked against itself and it hid a live
// defect. The web half derives ITS list independently, from what the client
// sources actually name, and the two are compared.
func TestRouteInventoryFixture(t *testing.T) {
	b := newBackend(t)
	// Every seam wired, because a nil seam leaves its routes registered anyway
	// (they answer 503) — the registration is what this fixture is about, and
	// the surface must not depend on which optional organs a process composes.
	srv := api.New(api.Config{
		Log: b.log, Sessions: b.store, Auth: fixedIdentity{"op"},
		Settings: fixedSettings{d: time.Second},
		HealthFn: func() api.Health { return api.Health{Ready: true} },
		DB:       b.db,
	})
	_ = srv.Handler()
	routes := srv.Routes()
	if len(routes) < 60 {
		t.Fatalf("the inventory holds %d routes, which is too few to be the real table", len(routes))
	}
	fx := routeInventory{
		Note: "Generated by internal/api (TestRouteInventoryFixture) from the mux's OWN registration calls, " +
			"not from a hand-kept list. The web suite compares it against the paths the client sources actually " +
			"name, so a route added with no consumer — or a client calling a route that does not exist — fails on " +
			"one side or the other (Spec S19.5 'the React SPA consumes every API built above').",
		Routes: routes,
	}
	raw, err := json.Marshal(fx)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	compareOrWriteFixture(t, "route-inventory", canonicalJSON(t, raw))
}

// TestRouteInventoryIsTheMuxsOwnList is the non-tautological control: the
// recorded list has to BE what the mux answers. A pattern recorded but never
// registered would make the fixture a fiction, so every GET route in it is
// asked for and must not 404 as an unrouted path.
func TestRouteInventoryIsTheMuxsOwnList(t *testing.T) {
	b := newBackend(t)
	srv := api.New(api.Config{
		Log: b.log, Sessions: b.store, Auth: fixedIdentity{"op"},
		Settings: fixedSettings{d: time.Second},
		HealthFn: func() api.Health { return api.Health{Ready: true} },
		DB:       b.db,
	})
	h := srv.Handler()
	checked := 0
	for _, r := range srv.Routes() {
		if r.Method != http.MethodGet || strings.Contains(r.Path, "{") {
			continue // wildcards need a real id; the literal GETs are the control
		}
		// A short deadline, because `/events` is a STREAM: it holds the
		// connection open by design and returns when its request context ends.
		// Every other handler answers long before this fires.
		ctx, cancel := context.WithTimeout(context.Background(), 150*time.Millisecond)
		rr := httptest.NewRecorder()
		h.ServeHTTP(rr, httptest.NewRequest(http.MethodGet, r.Path, nil).WithContext(ctx))
		cancel()
		checked++
		// An unrouted /api path gets http.ServeMux's OWN plain-text 404, whose
		// body is this exact literal (§41). A routed handler may legitimately
		// answer 404 too — an empty auth store has no session row — so the
		// status alone is not the discriminator; the mux's own body is.
		if rr.Body.String() == muxNotFound {
			t.Errorf("%s is in the inventory but the mux does not route it", r.Path)
		}
	}
	if checked < 8 {
		t.Fatalf("only %d literal GET routes were checked; the control is too thin", checked)
	}
	// And the other direction: a path NOT in the inventory really does get that
	// plain 404, so the assertion above is discriminating.
	rr := httptest.NewRecorder()
	h.ServeHTTP(rr, httptest.NewRequest(http.MethodGet, "/api/definitely-not-a-route", nil))
	if rr.Code != http.StatusNotFound || rr.Body.String() != muxNotFound {
		t.Fatalf("an unrouted /api path answered %d %q; the control above cannot discriminate",
			rr.Code, rr.Body.String())
	}
}
