// Package units renders the systemd unit set of Spec S01.2 — the process
// seam of Spec S01.3 made concrete: every organ its own unit, its own
// journal identity, its own restart policy.
//
// Units are GENERATED, NEVER INSTALLED by this code: output goes to stdout
// or an operator-chosen directory, and host changes (installing under
// /etc/systemd, systemctl calls) are a B0-gate operator decision
// (P3/STATE.md). Adopted organs (caddy, the watchlist executor, local-model
// units, tailscaled) ship their own units and are deliberately not
// generated here — replacing one is a unit + components.lock edit at the
// process/adoption seams (Spec S01.3).
//
// ⚙ values are rendered from the settings registry (shell.watchdog_sec,
// shell.journal_max_use). At B0 generation reads the declared defaults —
// override-aware regeneration needs the operator surfaces of later packets;
// regenerate + reinstall is the update path either way (restart-required
// posture, Spec S01.10).
package units

import (
	"fmt"
	"strings"
)

// A1 hostname commitment (Spec S01.8, amendment A1, operator 2026-07-19):
// the ts.net machine name is `sinet`. It is recorded here so every
// generated artifact that ever needs the hostname draws it from one place.
const (
	Hostname = "sinet"
	FQDN     = "sinet.tailfd0b1e.ts.net"
)

// DefaultBinaryPath is where the deploy step installs the one release
// artifact (Spec S01.5, S01.11) and therefore the ExecStart= prefix of
// every owned unit. Mode names are stable from B0-1, so these lines never
// change shape.
const DefaultBinaryPath = "/usr/local/bin/sinet"

// Settings is the units-facing view of the settings registry (Spec S01.10).
type Settings interface {
	Int(key string) (int64, error)
}

// Dotted ⚙ keys rendered into the unit set (owned by Spec S01).
const (
	keyWatchdogSec   = "shell.watchdog_sec"
	keyJournalMaxUse = "shell.journal_max_use"
)

// File is one generated configuration file.
type File struct {
	// Name is the file name (unit name, or a drop-in name whose intended
	// target path is stated in its header comment).
	Name string
	// Content is the complete file text.
	Content string
	// Draft marks a unit whose ExecStart (and therefore installability)
	// belongs to a later phase: generated for shape stability, not
	// installable yet.
	Draft bool
}

// Params configures generation.
type Params struct {
	// BinaryPath overrides DefaultBinaryPath.
	BinaryPath string
}

// header is the shared provenance banner.
func header() string {
	return fmt.Sprintf(`# Generated by 'sinet units' — Spec S01.2 unit set. Do not hand-edit;
# regenerate instead. Nothing installs this file: host changes are a
# B0-gate operator decision. Host identity (amendment A1): machine %q,
# tailnet FQDN %q.
`, Hostname, FQDN)
}

// hardening is the standard hardening set applied to every owned unit as
// far as compatible with its duty (Spec S01.2); a per-unit exception is
// recorded in the unit file with a reason.
const hardening = `# Standard hardening set (Spec S01.2).
ProtectSystem=strict
NoNewPrivileges=yes
PrivateTmp=yes
SystemCallFilter=@system-service
`

// staticUser pins every platform unit to the one static sinet user —
// DynamicUser= is NEVER used for state-owning units (UID recycling vs
// decade-lived DB files, Spec S01.1).
const staticUser = `User=sinet
Group=sinet
`

// Files renders the S01.2 unit set in deterministic order.
func Files(settings Settings, p Params) ([]File, error) {
	bin := p.BinaryPath
	if bin == "" {
		bin = DefaultBinaryPath
	}
	watchdogSec, err := settings.Int(keyWatchdogSec)
	if err != nil {
		return nil, fmt.Errorf("units: read ⚙ %s: %w", keyWatchdogSec, err)
	}
	journalMaxUse, err := settings.Int(keyJournalMaxUse)
	if err != nil {
		return nil, fmt.Errorf("units: read ⚙ %s: %w", keyJournalMaxUse, err)
	}
	return []File{
		controlService(bin, watchdogSec),
		brokerService(bin),
		engineTemplate(),
		runTemplate(bin),
		portpoolService(bin),
		journaldDropIn(journalMaxUse),
	}, nil
}

func controlService(bin string, watchdogSec int64) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Front chain (Spec S01.4): tailscale serve (tailnet-only TLS on %s,
# identity headers) -> caddy (routing; /events unbuffered) -> 127.0.0.1.
# This unit binds loopback only; the in-process listener lint refuses to
# start otherwise (P-T13-2, Spec S01.6 step 2).
[Unit]
Description=Sinet control plane (sole platform.db writer; Spec S01.2)
# The broker starts first: engines receive credentials at start and the
# control plane consumes broker operations (Spec S01.6).
After=network.target sinet-broker.service
Wants=sinet-broker.service

[Service]
Type=notify
ExecStart=%s control
`, FQDN, bin)
	fmt.Fprintf(&b, "# ⚙ shell.watchdog_sec (Spec S01.2): sd_notify heartbeat budget.\nWatchdogSec=%d\n", watchdogSec)
	b.WriteString(`Restart=on-failure
# /var/lib/sinet (platform.db home) and /etc/sinet (bootstrap config) —
# zero custom path code (Spec S01.11).
StateDirectory=sinet
ConfigurationDirectory=sinet
# MUST exceed the flush budget (Spec S01.6); the in-process shutdown budget
# is 20 s.
TimeoutStopSec=90
`)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return File{Name: "sinet-control.service", Content: b.String()}
}

func brokerService(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Separate process so the large-attack-surface control plane never holds
# decrypted member credentials (Spec S01.2, D2). UDS with peer-cred auth;
# no TCP listener. Broker internals — secrets at rest via systemd-creds +
# sops/age, LoadCredential= wiring — are Spec S11's and land at B1.
[Unit]
Description=Sinet credential broker (secrets never in run units; Spec S01.2)
Before=sinet-control.service
After=network.target

[Service]
Type=exec
ExecStart=%s broker
Restart=on-failure
`, bin)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return File{Name: "sinet-broker.service", Content: b.String()}
}

func engineTemplate() File {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString(`# DRAFT — not installable until B1: the ExecStart= invocation (per-user
# pinned 'opencode serve' on a per-user localhost port, credentials
# injected at start outside any sandbox, SPIKE P2-S3) is Spec S03's design.
# Directives below are the ones Spec S01.2 fixes for this template.
[Unit]
Description=Sinet engine instance for user %i (Spec S01.2)
After=sinet-broker.service
Wants=sinet-broker.service

[Service]
# ExecStart= lands at B1 (Spec S03).
Restart=on-failure
`)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	return File{Name: "sinet-engine@.service", Content: b.String(), Draft: true}
}

func runTemplate(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString(`# The fixed-ExecStart sandbox composition of Spec S11.8 Shape B: a
# root-installed template + a single name-scoped polkit grant. ExecStart is
# the run launcher (Spec S11.8) — fixed and non-agent-reachable; the control
# plane, as unprivileged sinet, writes only DATA (the per-run confinement/
# spawn record) to the spool file and starts the instance. Installing this
# template (root) and the ^sinet-run@.*\.service$ polkit rule is the operator
# gate step (no host changes at B1); per-run properties (RuntimeMaxSec= time
# ceiling, cgroup accounting) are set per instance at dispatch (Spec S01.2,
# S10). Wording reconciled to the multi-call binary (Spec S01.5): S11.8's
# /usr/lib/sinet/run-launch is this binary in the run-launch mode.
[Unit]
Description=Sinet run unit %i (one run's engine process in its sandbox; Spec S01.2/S11.8)

[Service]
# Harvest lane recipe (Spec S02.5): unit corpses must outlive the process
# tree so finished-during-outage results stay classifiable — never
# systemd-run --collect.
Type=exec
RemainAfterExit=yes
ExitType=cgroup
`)
	fmt.Fprintf(&b, "ExecStart=%s run-launch --job /run/sinet/jobs/%%i.json\n", bin)
	b.WriteString(`# Run units are never auto-restarted by PID 1: a dead run is recovered by
# the S02 recovery ladder (fork-from-checkpoint), a control-plane decision
# (Spec S01.2).
Restart=no
# Per-unit journald rate-limit overrides for chatty workers
# (LogRateLimitIntervalSec=/LogRateLimitBurst=) are set per instance
# (Spec S01.11).
`)
	b.WriteString(staticUser)
	return File{Name: "sinet-run@.service", Content: b.String()}
}

func portpoolService(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Port-pool daemon for preview allocation (Spec S01.2; consumer Spec S13).
# Loopback only, like every sinet unit (Spec S01.1).
[Unit]
Description=Sinet preview port-pool daemon (Spec S01.2)
After=network.target

[Service]
Type=exec
ExecStart=%s portpool
Restart=on-failure
`, bin)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return File{Name: "sinet-portpool.service", Content: b.String()}
}

func journaldDropIn(journalMaxUse int64) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Intended target: /etc/systemd/journald.conf.d/sinet.conf
# (restart-required ⚙; journald restart applies it).
[Journal]
# ⚙ shell.journal_max_use (Spec S01.11): journald is the ops log only and
# its total use is capped; the platform.db event log is the only audit
# truth.
SystemMaxUse=%d
`, journalMaxUse)
	return File{Name: "journald-sinet.conf", Content: b.String()}
}
