// Package units renders the systemd unit set of Spec S01.2 — the process
// seam of Spec S01.3 made concrete: every organ its own unit, its own
// journal identity, its own restart policy.
//
// Units are GENERATED, NEVER INSTALLED by this code: output goes to stdout
// or an operator-chosen directory, and host changes (installing under
// /etc/systemd, systemctl calls) are a B0-gate operator decision
// (P3/STATE.md). Adopted organs (caddy, the watchlist executor, local-model
// units, tailscaled) ship their own units and are deliberately not
// generated here — replacing one is a unit + components.lock edit at the
// process/adoption seams (Spec S01.3).
//
// ⚙ values are rendered from the settings registry (shell.watchdog_sec,
// shell.journal_max_use). At B0 generation reads the declared defaults —
// override-aware regeneration needs the operator surfaces of later packets;
// regenerate + reinstall is the update path either way (restart-required
// posture, Spec S01.10).
package units

import (
	"fmt"
	"strings"
	"time"
)

// A1 hostname commitment (Spec S01.8, amendment A1, operator 2026-07-19):
// the ts.net machine name is `sinet`. It is recorded here so every
// generated artifact that ever needs the hostname draws it from one place.
const (
	Hostname = "sinet"
	FQDN     = "sinet.tailfd0b1e.ts.net"
)

// DefaultBinaryPath is where the deploy step installs the one release
// artifact (Spec S01.5, S01.11) and therefore the ExecStart= prefix of
// every owned unit. Mode names are stable from B0-1, so these lines never
// change shape.
const DefaultBinaryPath = "/usr/local/bin/sinet"

// Settings is the units-facing view of the settings registry (Spec S01.10).
type Settings interface {
	Int(key string) (int64, error)
	Duration(key string) (time.Duration, error)
}

// Dotted ⚙ keys rendered into the unit set (owned by Spec S01, plus the S13.10
// backup cadences the persistent calendar timers derive from).
const (
	keyWatchdogSec     = "shell.watchdog_sec"
	keyJournalMaxUse   = "shell.journal_max_use"
	keyBackupInterval  = "backup.interval"       // seconds (snapshot cadence)
	keyBackupDrillEach = "backup.drill_interval" // months (restore-drill cadence)
)

// File is one generated configuration file.
type File struct {
	// Name is the file name (unit name, or a drop-in name whose intended
	// target path is stated in its header comment).
	Name string
	// Content is the complete file text.
	Content string
	// Draft marks a unit whose ExecStart (and therefore installability)
	// belongs to a later phase: generated for shape stability, not
	// installable yet.
	Draft bool
}

// Params configures generation.
type Params struct {
	// BinaryPath overrides DefaultBinaryPath.
	BinaryPath string
}

// header is the shared provenance banner.
func header() string {
	return fmt.Sprintf(`# Generated by 'sinet units' — Spec S01.2 unit set. Do not hand-edit;
# regenerate instead. Nothing installs this file: host changes are a
# B0-gate operator decision. Host identity (amendment A1): machine %q,
# tailnet FQDN %q.
`, Hostname, FQDN)
}

// hardening is the standard hardening set applied to every owned unit as
// far as compatible with its duty (Spec S01.2); a per-unit exception is
// recorded in the unit file with a reason.
const hardening = `# Standard hardening set (Spec S01.2).
ProtectSystem=strict
NoNewPrivileges=yes
PrivateTmp=yes
SystemCallFilter=@system-service
`

// staticUser pins every platform unit to the one static sinet user —
// DynamicUser= is NEVER used for state-owning units (UID recycling vs
// decade-lived DB files, Spec S01.1).
const staticUser = `User=sinet
Group=sinet
`

// Files renders the S01.2 unit set in deterministic order.
func Files(settings Settings, p Params) ([]File, error) {
	bin := p.BinaryPath
	if bin == "" {
		bin = DefaultBinaryPath
	}
	watchdogSec, err := settings.Int(keyWatchdogSec)
	if err != nil {
		return nil, fmt.Errorf("units: read ⚙ %s: %w", keyWatchdogSec, err)
	}
	journalMaxUse, err := settings.Int(keyJournalMaxUse)
	if err != nil {
		return nil, fmt.Errorf("units: read ⚙ %s: %w", keyJournalMaxUse, err)
	}
	backupInterval, err := settings.Duration(keyBackupInterval)
	if err != nil {
		return nil, fmt.Errorf("units: read ⚙ %s: %w", keyBackupInterval, err)
	}
	snapCal, err := onCalendarFromSeconds(int64(backupInterval.Seconds()))
	if err != nil {
		return nil, fmt.Errorf("units: ⚙ %s: %w", keyBackupInterval, err)
	}
	drillMonths, err := settings.Int(keyBackupDrillEach)
	if err != nil {
		return nil, fmt.Errorf("units: read ⚙ %s: %w", keyBackupDrillEach, err)
	}
	drillCal := onCalendarFromMonths(drillMonths)
	return []File{
		controlService(bin, watchdogSec),
		brokerService(bin),
		engineTemplate(),
		runTemplate(bin),
		portpoolService(bin),
		snapshotService(bin),
		snapshotTimer(snapCal, keyBackupInterval),
		restoreDrillService(bin),
		restoreDrillTimer(drillCal, keyBackupDrillEach),
		journaldDropIn(journalMaxUse),
	}, nil
}

func controlService(bin string, watchdogSec int64) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Front chain (Spec S01.4): tailscale serve (tailnet-only TLS on %s,
# identity headers) -> caddy (routing; /events unbuffered) -> 127.0.0.1.
# This unit binds loopback only; the in-process listener lint refuses to
# start otherwise (P-T13-2, Spec S01.6 step 2).
[Unit]
Description=Sinet control plane (sole platform.db writer; Spec S01.2)
# The broker starts first: engines receive credentials at start and the
# control plane consumes broker operations (Spec S01.6).
After=network.target sinet-broker.service
Wants=sinet-broker.service

[Service]
Type=notify
ExecStart=%s control
`, FQDN, bin)
	fmt.Fprintf(&b, "# ⚙ shell.watchdog_sec (Spec S01.2): sd_notify heartbeat budget.\nWatchdogSec=%d\n", watchdogSec)
	b.WriteString(`Restart=on-failure
# /var/lib/sinet (platform.db home) and /etc/sinet (bootstrap config) —
# zero custom path code (Spec S01.11).
StateDirectory=sinet
ConfigurationDirectory=sinet
# MUST exceed the flush budget (Spec S01.6); the in-process shutdown budget
# is 20 s.
TimeoutStopSec=90
`)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return File{Name: "sinet-control.service", Content: b.String()}
}

func brokerService(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Separate process so the large-attack-surface control plane never holds
# decrypted member credentials (Spec S01.2, D2). UDS with peer-cred auth;
# no TCP listener. Broker internals — secrets at rest via systemd-creds +
# sops/age, LoadCredential= wiring — are Spec S11's and land at B1.
[Unit]
Description=Sinet credential broker (secrets never in run units; Spec S01.2)
Before=sinet-control.service
After=network.target

[Service]
Type=exec
ExecStart=%s broker
Restart=on-failure
# Broker state root (socket + per-person stores): systemd provisions
# /var/lib/sinet and exports $STATE_DIRECTORY, which the broker's
# defaultStateDir honors — without it, ProtectSystem=strict leaves the
# broker no writable path and it dies at first mkdir (found at the B2-gate
# host install; Spec S01.2/S01.11 zero-custom-path-code posture).
StateDirectory=sinet
`, bin)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return File{Name: "sinet-broker.service", Content: b.String()}
}

func engineTemplate() File {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString(`# DRAFT — not installable until B1: the ExecStart= invocation (per-user
# pinned 'opencode serve' on a per-user localhost port, credentials
# injected at start outside any sandbox, SPIKE P2-S3) is Spec S03's design.
# Directives below are the ones Spec S01.2 fixes for this template.
[Unit]
Description=Sinet engine instance for user %i (Spec S01.2)
After=sinet-broker.service
Wants=sinet-broker.service

[Service]
# ExecStart= lands at B1 (Spec S03).
Restart=on-failure
`)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	return File{Name: "sinet-engine@.service", Content: b.String(), Draft: true}
}

func runTemplate(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString(`# The fixed-ExecStart sandbox composition of Spec S11.8 Shape B: a
# root-installed template + a single name-scoped polkit grant. ExecStart is
# the run launcher (Spec S11.8) — fixed and non-agent-reachable; the control
# plane, as unprivileged sinet, writes only DATA (the per-run confinement/
# spawn record) to the spool file and starts the instance. Installing this
# template (root) and the ^sinet-run@.*\.service$ polkit rule is the operator
# gate step (no host changes at B1); per-run properties (RuntimeMaxSec= time
# ceiling, cgroup accounting) are set per instance at dispatch (Spec S01.2,
# S10). Wording reconciled to the multi-call binary (Spec S01.5): S11.8's
# /usr/lib/sinet/run-launch is this binary in the run-launch mode.
[Unit]
Description=Sinet run unit %i (one run's engine process in its sandbox; Spec S01.2/S11.8)

[Service]
# Harvest lane recipe (Spec S02.5): unit corpses must outlive the process
# tree so finished-during-outage results stay classifiable — never
# systemd-run --collect.
Type=exec
RemainAfterExit=yes
ExitType=cgroup
`)
	fmt.Fprintf(&b, "ExecStart=%s run-launch --job /run/sinet/jobs/%%i.json\n", bin)
	b.WriteString(`# Run units are never auto-restarted by PID 1: a dead run is recovered by
# the S02 recovery ladder (fork-from-checkpoint), a control-plane decision
# (Spec S01.2).
Restart=no
# Per-unit journald rate-limit overrides for chatty workers
# (LogRateLimitIntervalSec=/LogRateLimitBurst=) are set per instance
# (Spec S01.11).
`)
	b.WriteString(staticUser)
	return File{Name: "sinet-run@.service", Content: b.String()}
}

func portpoolService(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Port-pool daemon for preview allocation (Spec S01.2; consumer Spec S13).
# Loopback only, like every sinet unit (Spec S01.1).
[Unit]
Description=Sinet preview port-pool daemon (Spec S01.2)
After=network.target

[Service]
Type=exec
ExecStart=%s portpool
Restart=on-failure
`, bin)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	b.WriteString(`
[Install]
WantedBy=multi-user.target
`)
	return File{Name: "sinet-portpool.service", Content: b.String()}
}

// snapshotService is the one-shot `sinet snapshot` service (Spec S13.10). Its
// live configuration — the private snapshot-repo URL, the broker git-ssh-key
// profile, the escrow identity path, the file stores — rides an EnvironmentFile
// the operator supplies at the B4 gate/bring-up, so the LIVE leg is pure config
// with no code change (R24). Generated, never installed.
func snapshotService(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# One-shot platform-state snapshot (Spec S13.10). Bring-up config
# (SINET_SNAPSHOT_REMOTE, SINET_SNAPSHOT_GIT_PROFILE, SINET_SNAPSHOT_IDENTITY,
# SINET_SNAPSHOT_STORES) rides /etc/sinet/snapshot.env — the operator supplies
# it at the B4 gate (the private repo designation + broker key enrollment are
# operator prerequisites; nothing is created automatically).
[Unit]
Description=Sinet platform-state snapshot (Spec S13.10)
After=sinet-broker.service
Wants=sinet-broker.service

[Service]
Type=oneshot
EnvironmentFile=-/etc/sinet/snapshot.env
ExecStart=%s snapshot --snapshot-remote ${SINET_SNAPSHOT_REMOTE} --git-profile ${SINET_SNAPSHOT_GIT_PROFILE} --identity ${SINET_SNAPSHOT_IDENTITY} ${SINET_SNAPSHOT_STORES}
StateDirectory=sinet
`, bin)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	return File{Name: "sinet-snapshot.service", Content: b.String(), Draft: true}
}

// snapshotTimer is the S01.7 PERSISTENT calendar timer for snapshots: a slot
// missed in suspend fires once on next activation (distinct from the in-process
// WAL/recovery tickers). OnCalendar derives from ⚙ backup.interval. Generated,
// never installed.
func snapshotTimer(onCalendar, key string) File {
	return calendarTimer("sinet-snapshot", "platform-state snapshot", onCalendar, key)
}

// restoreDrillService is the one-shot `sinet restore-drill` service (Spec
// S13.10): fetch the newest blob → verify against the ledger fail-closed →
// decrypt with the escrow identity → rebuild → integrity + S02.9. Generated,
// never installed.
func restoreDrillService(bin string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# One-shot verified-restore drill (Spec S13.10: a backup that is not
# restore-tested does not exist). Shares /etc/sinet/snapshot.env with the
# snapshot service. A fail-closed drill raises a High flag (S14).
[Unit]
Description=Sinet restore drill (Spec S13.10)
After=sinet-broker.service
Wants=sinet-broker.service

[Service]
Type=oneshot
EnvironmentFile=-/etc/sinet/snapshot.env
ExecStart=%s restore-drill --snapshot-remote ${SINET_SNAPSHOT_REMOTE} --git-profile ${SINET_SNAPSHOT_GIT_PROFILE} --identity ${SINET_SNAPSHOT_IDENTITY}
StateDirectory=sinet
`, bin)
	b.WriteString(staticUser)
	b.WriteString(hardening)
	return File{Name: "sinet-restore-drill.service", Content: b.String(), Draft: true}
}

// restoreDrillTimer is the S01.7 persistent calendar timer for the restore
// drill; OnCalendar derives from ⚙ backup.drill_interval. Generated, never
// installed.
func restoreDrillTimer(onCalendar, key string) File {
	return calendarTimer("sinet-restore-drill", "restore drill", onCalendar, key)
}

// calendarTimer renders a persistent (suspend-catch-up) calendar timer unit
// (Spec S01.7). Persistent=true is what makes a missed slot fire once on next
// activation.
func calendarTimer(unit, what, onCalendar, key string) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Persistent calendar timer for the %s (Spec S01.7: a slot missed in
# suspend fires once on next activation; NOT an in-process ticker). OnCalendar
# derives from ⚙ %s.
[Unit]
Description=Sinet %s schedule (Spec S13.10)

[Timer]
OnCalendar=%s
Persistent=true
Unit=%s.service

[Install]
WantedBy=timers.target
`, what, key, what, onCalendar, unit)
	return File{Name: unit + ".timer", Content: b.String(), Draft: true}
}

// onCalendarFromSeconds maps a ⚙ backup.interval (seconds) to a systemd
// OnCalendar expression (Spec S01.7). Sub-daily intervals that are whole-hour
// divisors of a day render as an hour step; a day renders daily; a week renders
// weekly; other whole-day intervals render as an approximate day step (a
// month-boundary caveat). A non-expressible interval is a LOUD error rather
// than a silently mis-scheduled timer.
func onCalendarFromSeconds(sec int64) (string, error) {
	if sec <= 0 {
		return "", fmt.Errorf("interval %ds is not positive", sec)
	}
	d := time.Duration(sec) * time.Second
	day := 24 * time.Hour
	switch {
	case d == day:
		return "*-*-* 00:00:00", nil
	case d == 7*day:
		return "Mon *-*-* 00:00:00", nil
	case d < day:
		if d%time.Hour != 0 || day%d != 0 {
			return "", fmt.Errorf("interval %s is not a whole-hour divisor of a day", d)
		}
		return fmt.Sprintf("*-*-* 0/%d:00:00", int(d/time.Hour)), nil
	case d%day == 0:
		return fmt.Sprintf("*-*-1/%d 00:00:00", int(d/day)), nil
	default:
		return "", fmt.Errorf("interval %s is not expressible as a persistent calendar timer", d)
	}
}

// onCalendarFromMonths maps a ⚙ backup.drill_interval (months) to a systemd
// OnCalendar expression: every n-th month on the 1st (a year-boundary caveat for
// n that does not divide 12). n=1 is monthly.
func onCalendarFromMonths(n int64) string {
	if n <= 1 {
		return "*-*-01 00:00:00"
	}
	return fmt.Sprintf("*-1/%d-01 00:00:00", n)
}

func journaldDropIn(journalMaxUse int64) File {
	var b strings.Builder
	b.WriteString(header())
	fmt.Fprintf(&b, `# Intended target: /etc/systemd/journald.conf.d/sinet.conf
# (restart-required ⚙; journald restart applies it).
[Journal]
# ⚙ shell.journal_max_use (Spec S01.11): journald is the ops log only and
# its total use is capped; the platform.db event log is the only audit
# truth.
SystemMaxUse=%d
`, journalMaxUse)
	return File{Name: "journald-sinet.conf", Content: b.String()}
}
