import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'

import { Inbox, InboxItem } from './Inbox'
import { PushDevices } from './PushDevices'
import { fixtures, scriptedFetch, signedIn, FakeSource } from './doubles'
import { EventStream } from './events'
import { matchRoute, hrefFor } from './routes'
import {
  availability,
  decodeVAPIDKey,
  enrol,
  enrolmentBody,
  reconcileBadge,
  swPath,
  unenrol,
  type PushEnv,
  type PushManagerLike,
  type PushSubscriptionLike,
} from './push'
import { act } from 'react'

import { flush, mount, settle } from './testing'

import navigateFixture from './fixtures/api/push-navigate.json?raw'
import pushSubscriptionsRaw from './fixtures/api/push-subscriptions.json?raw'
import pushSubscriptionsMemberRaw from './fixtures/api/push-subscriptions-member.json?raw'

/**
 * The S15.11 device half (B6-9), driven offline.
 *
 * Nothing here opens a connection: the fetch double is scripted, the push
 * manager is a stand-in for a browser API jsdom does not implement, and
 * VITE_SINET_ADDR stays unset.
 */

const pushView = () => JSON.parse(pushSubscriptionsRaw) as Record<string, unknown>
/** The endpoint the fixture world enrolled alice's phone with, so a test can
 *  hold a subscription the SERVED list really carries. */
const fixtureAliceEndpoint = 'https://web.push.apple.com/QDzVuUUFuFXY-fixture-alice-phone'
const pushViewMember = () => JSON.parse(pushSubscriptionsMemberRaw) as Record<string, unknown>

// ── the cross-language deep-link tie (rubric 8) ────────────────────────────

describe('a push navigate path resolves to the card it names', () => {
  const fx = JSON.parse(navigateFixture) as { cases: { card_id: string; path: string }[] }

  test('every server-composed path round-trips through the router', () => {
    // The floor: this fixture is GENERATED by internal/api, so an empty one
    // would make the whole tie vacuous.
    expect(fx.cases.length).toBeGreaterThan(5)
    for (const c of fx.cases) {
      const match = matchRoute(c.path)
      expect(match.route.id, `${c.path} did not resolve to the inbox card surface`).toBe('inbox-item')
      expect(match.params.id, `${c.path} resolved to a DIFFERENT card id`).toBe(c.card_id)
    }
  })

  test('and the client composes the same path the server did', () => {
    // The other direction: the SPA's own link builder must produce byte-for-byte
    // what the notifier put in the payload. If these ever diverge, a tapped
    // notification and a clicked link go to different places.
    for (const c of fx.cases) {
      expect(hrefFor('inbox-item', { id: c.card_id }), `hrefFor disagrees with the server for ${c.card_id}`).toBe(c.path)
    }
  })

  test('the tie is not vacuous: the ids really do carry the hard characters', () => {
    const ids = fx.cases.map((c) => c.card_id).join('')
    expect(ids).toContain(':')
    expect(ids).toContain('#')
    expect(ids).toContain('')
    // And at least one path really is escaped, so "round-trips" is a statement
    // about encoding rather than about ids that needed none.
    expect(fx.cases.some((c) => c.path.includes('%'))).toBe(true)
  })
})

// ── availability: four different facts, four different reasons ─────────────

function env(over: Partial<PushEnv> = {}): PushEnv {
  return {
    hasPushManager: true,
    permission: 'default',
    installed: false,
    origin: 'https://sinet.example.ts.net',
    serviceWorker: undefined,
    windowPushManager: undefined,
    ...over,
  }
}

describe('every unavailable state renders its own reason', () => {
  test('no push API and not installed says how to install', () => {
    const a = availability(env({ hasPushManager: false }))
    expect(a.state).toBe('unsupported')
    if (a.state !== 'unsupported') return
    expect(a.installHint).toBeDefined()
    expect(a.installHint).toContain('Add to Home Screen')
    expect(a.installHint).toContain('18.4')
  })

  test('no push API while ALREADY installed does not tell somebody to install', () => {
    const a = availability(env({ hasPushManager: false, installed: true }))
    expect(a.state).toBe('unsupported')
    if (a.state !== 'unsupported') return
    expect(a.installHint).toBeUndefined()
    expect(a.reason).toContain('16.4')
  })

  test('blocked permission says the browser will not let us ask again', () => {
    const a = availability(env({ permission: 'denied', serviceWorker: fakeContainer() }))
    expect(a.state).toBe('denied')
    if (a.state !== 'denied') return
    expect(a.reason).toContain('blocked')
  })

  test('the declarative path alone is enough', () => {
    expect(availability(env({ windowPushManager: fakeManager(), hasPushManager: false })).state).toBe('available')
  })

  test('the classic path needs BOTH a worker registrar and the Push API', () => {
    expect(availability(env({ serviceWorker: fakeContainer(), hasPushManager: true })).state).toBe('available')
    expect(availability(env({ serviceWorker: fakeContainer(), hasPushManager: false })).state).toBe('unsupported')
  })
})

// ── subscribe/unsubscribe, and the gesture rule ────────────────────────────

function fakeSubscription(endpoint = 'https://web.push.apple.com/abc'): PushSubscriptionLike & { unsubscribed: boolean } {
  const s = {
    endpoint,
    unsubscribed: false,
    toJSON: () => ({ endpoint, keys: { p256dh: 'BPUB', auth: 'AUTH' } }),
    unsubscribe: async () => {
      s.unsubscribed = true
      return true
    },
  }
  return s
}

function fakeManager(existing: PushSubscriptionLike | null = null) {
  const calls: { userVisibleOnly: boolean; applicationServerKey: Uint8Array }[] = []
  let held = existing
  const manager: PushManagerLike & { calls: typeof calls } = {
    calls,
    getSubscription: async () => held,
    subscribe: async (options) => {
      calls.push(options)
      held = fakeSubscription()
      return held
    },
  }
  return manager
}

function fakeContainer(manager = fakeManager()) {
  const registered: string[] = []
  return {
    registered,
    register: async (script: string) => {
      registered.push(script)
      return { pushManager: manager }
    },
    ready: Promise.resolve({ pushManager: manager }),
  }
}

describe('enrolling this device', () => {
  test('asks for permission inside the act, and posts the browser’s own subscription', async () => {
    const manager = fakeManager()
    let asked = 0
    const e = env({
      windowPushManager: manager,
      requestPermission: async () => {
        asked++
        return 'granted'
      },
    })
    const log = scriptedFetch({ 'POST /api/push/subscriptions': { body: { replaced: false } } })

    await enrol(e, 'BFFcPW6545a5BNP-yn9U_c0MwemXvzddylFa0KbDtANfRTa-OlDzGPv5pUdZAqIhUCvvDVfgjFOyzApW8X2fk1Q', 'my phone')

    expect(asked).toBe(1)
    // `userVisibleOnly: true` is mandatory: Chrome and Edge reject a subscribe
    // without it and Safari revokes permission for an invisible push.
    expect(manager.calls[0].userVisibleOnly).toBe(true)
    expect(manager.calls[0].applicationServerKey).toBeInstanceOf(Uint8Array)
    expect(manager.calls[0].applicationServerKey.length).toBe(65)

    expect(log.calls).toHaveLength(1)
    expect(log.calls[0].path).toBe('/api/push/subscriptions')
    expect(log.calls[0].body).toEqual({
      endpoint: 'https://web.push.apple.com/abc',
      keys: { p256dh: 'BPUB', auth: 'AUTH' },
      origin: 'https://sinet.example.ts.net',
      label: 'my phone',
    })
  })

  test('a refused permission enrols nothing and says so', async () => {
    const e = env({ windowPushManager: fakeManager(), requestPermission: async () => 'denied' })
    const log = scriptedFetch({})
    await expect(enrol(e, 'BPUB', '')).rejects.toThrow(/not allowed/)
    expect(log.calls).toHaveLength(0)
  })

  test('an already-granted permission is not re-asked', async () => {
    const manager = fakeManager()
    let asked = 0
    const e = env({
      windowPushManager: manager,
      permission: 'granted',
      requestPermission: async () => {
        asked++
        return 'granted'
      },
    })
    scriptedFetch({ 'POST /api/push/subscriptions': { body: { replaced: false } } })
    await enrol(e, 'BPUB', '')
    expect(asked).toBe(0)
  })

  test('the classic path registers the push-only worker at the root scope', async () => {
    const container = fakeContainer()
    const e = env({ serviceWorker: container, permission: 'granted' })
    scriptedFetch({ 'POST /api/push/subscriptions': { body: { replaced: false } } })
    await enrol(e, 'BPUB', '')
    expect(container.registered).toEqual([swPath])
  })

  test('unenrolling tells the platform BEFORE it forgets the subscription', async () => {
    const held = fakeSubscription('https://web.push.apple.com/leaving')
    const manager = fakeManager(held)
    const log = scriptedFetch({ 'POST /api/push/subscriptions/remove': { body: { applied: true } } })
    await unenrol(env({ windowPushManager: manager, permission: 'granted' }))
    // The order is the point: a browser that forgot first would leave a row
    // this page can never clean up again.
    expect(log.calls[0].body).toEqual({ endpoint: 'https://web.push.apple.com/leaving' })
    expect(held.unsubscribed).toBe(true)
  })
})

/**
 * D13, CORRECTED. This used to assert that no rendered string contained a push
 * host — under a heading about never rendering an endpoint — over a body that
 * has no endpoint field at all. It could not fail, which is the inert-probe
 * class this packet was told not to create.
 *
 * What CAN fail is the body itself: it is regenerated from the real handler and
 * byte-compared by the Go suite, so if the server ever started serving an
 * endpoint this fires here on the very next regeneration. The render-side
 * statement follows from it — a view cannot display a field it was never sent —
 * and the store-side wall is `TestMetadataNeverCarriesTheEndpoint`.
 */
test('the SERVED device bodies carry no endpoint and no key material', () => {
  for (const [name, body] of [
    ['operator', pushView()],
    ['member', pushViewMember()],
  ] as const) {
    const subs = body.subscriptions as Record<string, unknown>[]
    expect(subs.length, `the ${name} body is empty, so this proves nothing`).toBeGreaterThan(0)
    for (const s of subs) {
      for (const [k, v] of Object.entries(s)) {
        // `origin` is the ONE URL on this wire and it is deliberate: it is the
        // enrolling page's own address, which is this device's deep-link prefix
        // (OQ7). It is not a capability — it is where the workspace lives.
        if (k === 'origin') continue
        expect(typeof v === 'string' && v.includes('://'), `${name}: field ${k} carries a URL`).toBe(false)
      }
      expect(String(s.origin), `${name}: origin is not a bare origin`).toMatch(/^https?:\/\/[^/]+$/)
      expect(Object.keys(s), `${name}: an endpoint field appeared on the wire`).not.toContain('endpoint')
      expect(Object.keys(s)).not.toContain('p256dh')
      expect(Object.keys(s)).not.toContain('auth')
      // The positive control: the row IS named, by the hash.
      expect(String(s.endpoint_hash)).toMatch(/^[0-9a-f]{64}$/)
    }
  }
})

test('the VAPID key comes from the served read, never from a constant', () => {
  const served = (pushView().vapid_public_key as string) ?? ''
  expect(served.length).toBeGreaterThan(80)
  const bytes = decodeVAPIDKey(served)
  expect(bytes.length).toBe(65)
  expect(bytes[0]).toBe(0x04)
  // The negative: no source file under web/src carries a key literal.
  // The scan covers the SHIPPED SERVICE WORKER too (drain r1, D14): sw.js
  // re-subscribes on a rotation and is precisely where an inline
  // applicationServerKey would be tempting, and it sits outside `src`.
  const scanned: Record<string, string> = {
    ...(import.meta.glob('./**/*.{ts,tsx}', { query: '?raw', import: 'default', eager: true }) as Record<string, string>),
    ...(import.meta.glob('../public/*.js', { query: '?raw', import: 'default', eager: true }) as Record<string, string>),
  }
  expect(Object.keys(scanned)).toContain('../public/sw.js')
  const hits = Object.entries(scanned)
    .filter(([p]) => !p.endsWith('push.test.tsx'))
    .filter(([, text]) => text.includes(served))
    .map(([p]) => p)
  expect(hits, 'the served application server key is hard-coded in the shipped tree').toEqual([])
  // The probe: the scan can fail.
  expect(Object.entries({ './planted.ts': `const k = '${served}'` }).filter(([, t]) => t.includes(served))).toHaveLength(1)
})

test('enrolmentBody refuses a subscription with no key material', () => {
  const broken: PushSubscriptionLike = {
    endpoint: 'https://push.example/x',
    toJSON: () => ({ endpoint: 'https://push.example/x' }),
    unsubscribe: async () => true,
  }
  expect(enrolmentBody(broken, 'https://sinet.example.ts.net', '')).toBeNull()
})

// ── the panel ──────────────────────────────────────────────────────────────

function panelRoutes(view: Record<string, unknown> = pushView()) {
  return {
    'GET /api/auth/session': signedIn,
    'GET /api/push/subscriptions': { body: view },
  }
}

describe('the “This device” panel', () => {
  beforeEach(() => {
    FakeSource.reset()
  })
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  const stream = () => new EventStream({ createEventSource: (url) => new FakeSource(url) })

  test('renders the served device list as METADATA and never an endpoint', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    const text = ui.container.textContent ?? ''
    expect(text).toContain('Alice’s phone')
    expect(text).toContain('Op’s laptop')
    expect(text).toContain('every device enrolled in this household')
    // The walk really does see the rendered values. It walks rather than
    // serializing, because serializing would put a token this tree's own escape
    // scan forbids into this file (the §43 precedent).
    expect(renderedStrings(ui.container).some((v) => v.includes('Alice’s phone'))).toBe(true)
    ui.unmount()
  })

  test('a member’s body is a NARROWER reading and says which one it is', async () => {
    scriptedFetch(panelRoutes(pushViewMember()))
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    const text = ui.container.textContent ?? ''
    expect(text).toContain('your own enrolled devices')
    expect(text).not.toContain('Op’s laptop')
    ui.unmount()
  })

  test('states what leaves this machine, from the SERVER’s own sentence', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ windowPushManager: fakeManager() })} />)
    await flush()
    expect(ui.container.textContent).toContain(pushView().observable as string)
    ui.unmount()
  })

  test('NOTHING asks for permission on mount', async () => {
    let asked = 0
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices
        stream={stream()}
        env={env({
          windowPushManager: fakeManager(),
          requestPermission: async () => {
            asked++
            return 'granted'
          },
        })}
      />,
    )
    await flush()
    expect(asked, 'a permission prompt fired on mount, outside any user gesture').toBe(0)
    ui.unmount()
  })

  test('an unsupported browser renders its reason and offers no control', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    expect(ui.container.querySelector('[data-push-state="unsupported"]')?.textContent).toContain('Add to Home Screen')
    expect(ui.container.querySelector('.push-device button')).toBeNull()
    ui.unmount()
  })

  test('a blocked browser says the browser will not let us ask again', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices stream={stream()} env={env({ windowPushManager: fakeManager(), permission: 'denied' })} />,
    )
    await flush()
    expect(ui.container.querySelector('[data-push-state="denied"]')?.textContent).toContain('blocked')
    ui.unmount()
  })

  /**
   * settleDevice waits for the panel's own device READ to land.
   *
   * It is a bounded wait rather than a fixed number of `flush()` calls because
   * the read hashes the browser's endpoint through `crypto.subtle.digest`, whose
   * promise is settled by the platform rather than by the microtask queue —
   * draining microtasks a fixed number of times is a race, and it flaked. This
   * asserts the same thing; it just stops asserting it before the answer exists.
   */
  const settleDevice = async (ui: { container: HTMLElement }, state: string) => {
    for (let i = 0; i < 20; i++) {
      if (ui.container.querySelector(`[data-push-state="${state}"]`)) return
      await settle(1)
    }
  }

  test('a device the platform DOES list renders enrolled — the control D10 was missing', async () => {
    // The endpoint the fixture's own alice row was enrolled with, so the hash
    // this page computes matches a served one. Without this the enrolled happy
    // path was never rendered by any test, while a comment claimed it was.
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices
        stream={stream()}
        env={env({ windowPushManager: fakeManager(fakeSubscription(fixtureAliceEndpoint)), permission: 'granted' })}
      />,
    )
    await flush()
    await settleDevice(ui, 'enrolled')
    expect(ui.container.querySelector('[data-push-state="enrolled"]')).not.toBeNull()
    expect(ui.container.textContent).toContain('This device is enrolled')
    // And the enrol control is gone, because there is nothing left to enrol.
    const buttons = [...ui.container.querySelectorAll('.push-device button')].map((b) => b.textContent ?? '')
    expect(buttons).toEqual(['Stop notifications on this device'])
    ui.unmount()
  })

  test('pressing Enrol actually enrols, and pressing Stop actually removes (drain r1, D8)', async () => {
    // The unit tests cover `enrol`/`unenrol` and the mount tests cover the
    // panel; nothing joined them, so removing BOTH onClick handlers left the
    // suite green and rubric item 2's "unsubscribe works" was not driven.
    const manager = fakeManager()
    const log = scriptedFetch({
      ...panelRoutes(),
      'POST /api/push/subscriptions': { body: { replaced: false } },
      'POST /api/push/subscriptions/remove': { body: { applied: true } },
    })
    const ui = mount(
      <PushDevices
        stream={stream()}
        env={env({ windowPushManager: manager, permission: 'granted', origin: 'https://sinet.example.ts.net' })}
      />,
    )
    await flush()
    await settleDevice(ui, 'not-enrolled')

    const enrolButton = [...ui.container.querySelectorAll('.push-device button')].find((b) =>
      (b.textContent ?? '').startsWith('Enrol'),
    ) as HTMLButtonElement
    expect(enrolButton, 'no enrol control rendered').toBeTruthy()
    act(() => enrolButton.click())
    await flush()
    await settle(2)

    const posted = log.calls.filter((c) => c.method === 'POST' && c.path === '/api/push/subscriptions')
    expect(posted, 'pressing Enrol posted nothing').toHaveLength(1)
    expect(posted[0].body).toMatchObject({ origin: 'https://sinet.example.ts.net' })
    expect(manager.calls[0].userVisibleOnly).toBe(true)

    // Now the stop control, which is the half rubric 2 names explicitly.
    await settleDevice(ui, 'unknown-subscription')
    const stopButton = [...ui.container.querySelectorAll('.push-device button')].find((b) =>
      (b.textContent ?? '').startsWith('Stop'),
    ) as HTMLButtonElement
    expect(stopButton, 'no stop control rendered after enrolling').toBeTruthy()
    act(() => stopButton.click())
    await flush()
    await settle(2)
    expect(
      log.calls.filter((c) => c.path === '/api/push/subscriptions/remove'),
      'pressing Stop removed nothing',
    ).toHaveLength(1)
    ui.unmount()
  })

  test('a subscription the platform does not list is stated, not glossed', async () => {
    // The browser holds one; the served list carries a DIFFERENT hash. Saying
    // "enrolled" would be false and saying "not enrolled" would be worse.
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices
        stream={stream()}
        env={env({ windowPushManager: fakeManager(fakeSubscription('https://web.push.apple.com/unknown-one')), permission: 'granted' })}
      />,
    )
    await flush()
    await settleDevice(ui, 'unknown-subscription')
    expect(ui.container.querySelector('[data-push-state="unknown-subscription"]')).not.toBeNull()
    // The control: the SAME world with the endpoint the served list DOES carry
    // renders enrolled, so this is about the mismatch and not about a branch
    // that always fires.
    expect(ui.container.textContent).toContain('does not have on file')
    ui.unmount()
  })

})

/** renderedStrings collects every text node and every attribute value under a
 *  node — the whole rendered surface, without serializing it to markup. */
function renderedStrings(root: Element): string[] {
  const out: string[] = []
  const walk = (el: Element) => {
    for (const attr of Array.from(el.attributes)) out.push(attr.value)
    for (const child of Array.from(el.childNodes)) {
      if (child.nodeType === 3) out.push(child.textContent ?? '')
      else if (child.nodeType === 1) walk(child as Element)
    }
  }
  walk(root)
  return out
}

// ── the badge is reconciled from the served inbox count (drain r1, D2) ─────

describe('the home-screen badge agrees with the queue after an answer', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
    vi.restoreAllMocks()
  })

  const badgeSpies = () => {
    const set = vi.fn(() => Promise.resolve())
    const clear = vi.fn(() => Promise.resolve())
    Object.defineProperty(navigator, 'setAppBadge', { value: set, configurable: true })
    Object.defineProperty(navigator, 'clearAppBadge', { value: clear, configurable: true })
    return { set, clear }
  }

  test('mounting the inbox writes the SERVED count', async () => {
    const { set } = badgeSpies()
    const body = fixtures.approvalsMine()
    const count = (body.items as unknown[]).length
    expect(count).toBeGreaterThan(1)
    scriptedFetch({ 'GET /api/approvals': { body } })
    const ui = mount(<Inbox stream={new EventStream({ createEventSource: (u) => new FakeSource(u) })} />)
    await flush()
    // The number is the length of the list actually on screen — the property
    // OQ5 calls glance agreement, checked against the DOM rather than against
    // the same variable the badge came from.
    expect(ui.container.querySelectorAll('.cards > li')).toHaveLength(count)
    expect(set).toHaveBeenCalledWith(count)
    ui.unmount()
  })

  test('an emptied queue CLEARS the badge rather than leaving the last pushed count', async () => {
    // This is the drill's own step 13: a card was answered, so the badge must
    // come down. Before this the badge held its last PUSHED value for up to a
    // full cadence, and the runbook's acceptance criterion could not be met.
    const { set, clear } = badgeSpies()
    scriptedFetch({ 'GET /api/approvals': { body: { items: [], cursor: 1 } } })
    const ui = mount(<Inbox stream={new EventStream({ createEventSource: (u) => new FakeSource(u) })} />)
    await flush()
    expect(clear).toHaveBeenCalled()
    expect(set).not.toHaveBeenCalled()
    ui.unmount()
  })

  test('the deep-link surface reconciles too — it is where a tapped notification lands', async () => {
    const { set } = badgeSpies()
    const body = fixtures.approvalsMine()
    const first = (body.items as { id: string }[])[0]
    scriptedFetch({ 'GET /api/approvals': { body } })
    const ui = mount(
      <InboxItem id={first.id} stream={new EventStream({ createEventSource: (u) => new FakeSource(u) })} />,
    )
    await flush()
    expect(set).toHaveBeenCalledWith((body.items as unknown[]).length)
    ui.unmount()
  })

  test('a browser with no Badging API is not an error', () => {
    // Most browsers have none, and the panel must not fail a render over it.
    const nav = navigator as unknown as Record<string, unknown>
    delete nav.setAppBadge
    delete nav.clearAppBadge
    expect(() => reconcileBadge(3)).not.toThrow()
    expect(() => reconcileBadge(0)).not.toThrow()
  })
})

// ── D8 pass II: the panel says what enrolment IS, and teaches when empty ───

describe('the push panel explains itself (P3-UI-6)', () => {
  beforeEach(() => {
    FakeSource.reset()
  })
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  const stream = () => new EventStream({ createEventSource: (url) => new FakeSource(url) })

  test('the panel-grain what-line says enrolment is per DEVICE and is not a setting', async () => {
    // A SUPPORTED browser, because the served observable sentence renders
    // inside the device block and the unsupported arm returns before it.
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ windowPushManager: fakeManager() })} />)
    await flush()
    const what = ui.container.querySelector('[data-panel-what="push"]')?.textContent ?? ''

    expect(what, 'the panel does not say what enrolment is').toContain('per DEVICE')
    expect(what).toContain('this browser on this machine')
    // §43-B: this panel touches no ⚙ registry key, and the line says so rather
    // than letting a reader inside the settings tab assume it is one.
    expect(what, 'the line lets enrolment read as a setting').toContain('not a setting')
    expect(what).toContain("changes the platform's configuration")

    // WHAT LEAVES THIS MACHINE IS THE SERVER'S SENTENCE, not this line's: the
    // S15.11/S01.8 observable statement renders verbatim and is not paraphrased
    // here, so a client-authored summary can never disagree with it.
    const observable = pushView().observable as string
    expect(ui.container.textContent, 'the served observable sentence was dropped').toContain(observable)
    expect(what, 'the what-line re-typed the served observable sentence').not.toContain(observable)
    ui.unmount()
  })

  test('an empty device list TEACHES what puts a row there — and teaches nothing while the read is in flight', async () => {
    scriptedFetch({ ...panelRoutes(), 'GET /api/push/subscriptions': { body: { ...pushView(), subscriptions: [] } } })
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    const text = ui.container.textContent ?? ''
    expect(text).toContain('No device is enrolled.')
    expect(text, 'the empty state teaches nothing about what adds a row').toContain('when a device is enrolled')
    expect(text, 'the empty state does not say what "none" means').toContain('nothing is sent anywhere')
    ui.unmount()

    // The D1 shape: this panel's OWN read never answers, so nothing may teach.
    scriptedFetch({ ...panelRoutes(), 'GET /api/push/subscriptions': { pending: true } })
    const waiting = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    expect(waiting.container.textContent, 'a teaching empty rendered over a read that had not answered').not.toContain(
      'No device is enrolled.',
    )
    waiting.unmount()
  })

  test('the restyled panel pins no pixel width, so a phone still enrols a device', async () => {
    const pinned = /w-\[\d+px\]|min-w-\[\d+px\]|max-w-\[\d+px\]/
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ windowPushManager: fakeManager(), permission: 'granted' })} />)
    await flush()
    const nodes = [...ui.container.querySelectorAll('[data-panel-what="push"], [data-push-scope], [data-push-state]')]
    expect(nodes.length, 'the walk found none of the panel renders').toBeGreaterThan(1)
    for (const n of nodes) {
      expect(pinned.test((n as HTMLElement).className.toString()), 'a panel render pins a pixel width').toBe(false)
      expect(/\d+px/.test(n.getAttribute('style') ?? ''), 'a panel render pins an inline width').toBe(false)
    }
    // Both-way probe on the detector.
    expect(pinned.test('w-[380px] flex')).toBe(true)
    expect(pinned.test('max-w-prose text-sm text-muted-foreground')).toBe(false)
    ui.unmount()
  })
})
