import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'

import { PushDevices } from './PushDevices'
import { scriptedFetch, signedIn, FakeSource } from './doubles'
import { EventStream } from './events'
import { matchRoute, hrefFor } from './routes'
import {
  availability,
  decodeVAPIDKey,
  enrol,
  enrolmentBody,
  swPath,
  unenrol,
  type PushEnv,
  type PushManagerLike,
  type PushSubscriptionLike,
} from './push'
import { flush, mount } from './testing'

import navigateFixture from './fixtures/api/push-navigate.json?raw'
import pushSubscriptionsRaw from './fixtures/api/push-subscriptions.json?raw'
import pushSubscriptionsMemberRaw from './fixtures/api/push-subscriptions-member.json?raw'

/**
 * The S15.11 device half (B6-9), driven offline.
 *
 * Nothing here opens a connection: the fetch double is scripted, the push
 * manager is a stand-in for a browser API jsdom does not implement, and
 * VITE_SINET_ADDR stays unset.
 */

const pushView = () => JSON.parse(pushSubscriptionsRaw) as Record<string, unknown>
const pushViewMember = () => JSON.parse(pushSubscriptionsMemberRaw) as Record<string, unknown>

// ── the cross-language deep-link tie (rubric 8) ────────────────────────────

describe('a push navigate path resolves to the card it names', () => {
  const fx = JSON.parse(navigateFixture) as { cases: { card_id: string; path: string }[] }

  test('every server-composed path round-trips through the router', () => {
    // The floor: this fixture is GENERATED by internal/api, so an empty one
    // would make the whole tie vacuous.
    expect(fx.cases.length).toBeGreaterThan(5)
    for (const c of fx.cases) {
      const match = matchRoute(c.path)
      expect(match.route.id, `${c.path} did not resolve to the inbox card surface`).toBe('inbox-item')
      expect(match.params.id, `${c.path} resolved to a DIFFERENT card id`).toBe(c.card_id)
    }
  })

  test('and the client composes the same path the server did', () => {
    // The other direction: the SPA's own link builder must produce byte-for-byte
    // what the notifier put in the payload. If these ever diverge, a tapped
    // notification and a clicked link go to different places.
    for (const c of fx.cases) {
      expect(hrefFor('inbox-item', { id: c.card_id }), `hrefFor disagrees with the server for ${c.card_id}`).toBe(c.path)
    }
  })

  test('the tie is not vacuous: the ids really do carry the hard characters', () => {
    const ids = fx.cases.map((c) => c.card_id).join('')
    expect(ids).toContain(':')
    expect(ids).toContain('#')
    expect(ids).toContain('')
    // And at least one path really is escaped, so "round-trips" is a statement
    // about encoding rather than about ids that needed none.
    expect(fx.cases.some((c) => c.path.includes('%'))).toBe(true)
  })
})

// ── availability: four different facts, four different reasons ─────────────

function env(over: Partial<PushEnv> = {}): PushEnv {
  return {
    hasPushManager: true,
    permission: 'default',
    installed: false,
    origin: 'https://sinet.example.ts.net',
    serviceWorker: undefined,
    windowPushManager: undefined,
    ...over,
  }
}

describe('every unavailable state renders its own reason', () => {
  test('no push API and not installed says how to install', () => {
    const a = availability(env({ hasPushManager: false }))
    expect(a.state).toBe('unsupported')
    if (a.state !== 'unsupported') return
    expect(a.installHint).toBeDefined()
    expect(a.installHint).toContain('Add to Home Screen')
    expect(a.installHint).toContain('18.4')
  })

  test('no push API while ALREADY installed does not tell somebody to install', () => {
    const a = availability(env({ hasPushManager: false, installed: true }))
    expect(a.state).toBe('unsupported')
    if (a.state !== 'unsupported') return
    expect(a.installHint).toBeUndefined()
    expect(a.reason).toContain('16.4')
  })

  test('blocked permission says the browser will not let us ask again', () => {
    const a = availability(env({ permission: 'denied', serviceWorker: fakeContainer() }))
    expect(a.state).toBe('denied')
    if (a.state !== 'denied') return
    expect(a.reason).toContain('blocked')
  })

  test('the declarative path alone is enough', () => {
    expect(availability(env({ windowPushManager: fakeManager(), hasPushManager: false })).state).toBe('available')
  })

  test('the classic path needs BOTH a worker registrar and the Push API', () => {
    expect(availability(env({ serviceWorker: fakeContainer(), hasPushManager: true })).state).toBe('available')
    expect(availability(env({ serviceWorker: fakeContainer(), hasPushManager: false })).state).toBe('unsupported')
  })
})

// ── subscribe/unsubscribe, and the gesture rule ────────────────────────────

function fakeSubscription(endpoint = 'https://web.push.apple.com/abc'): PushSubscriptionLike & { unsubscribed: boolean } {
  const s = {
    endpoint,
    unsubscribed: false,
    toJSON: () => ({ endpoint, keys: { p256dh: 'BPUB', auth: 'AUTH' } }),
    unsubscribe: async () => {
      s.unsubscribed = true
      return true
    },
  }
  return s
}

function fakeManager(existing: PushSubscriptionLike | null = null) {
  const calls: { userVisibleOnly: boolean; applicationServerKey: Uint8Array }[] = []
  let held = existing
  const manager: PushManagerLike & { calls: typeof calls } = {
    calls,
    getSubscription: async () => held,
    subscribe: async (options) => {
      calls.push(options)
      held = fakeSubscription()
      return held
    },
  }
  return manager
}

function fakeContainer(manager = fakeManager()) {
  const registered: string[] = []
  return {
    registered,
    register: async (script: string) => {
      registered.push(script)
      return { pushManager: manager }
    },
    ready: Promise.resolve({ pushManager: manager }),
  }
}

describe('enrolling this device', () => {
  test('asks for permission inside the act, and posts the browser’s own subscription', async () => {
    const manager = fakeManager()
    let asked = 0
    const e = env({
      windowPushManager: manager,
      requestPermission: async () => {
        asked++
        return 'granted'
      },
    })
    const log = scriptedFetch({ 'POST /api/push/subscriptions': { body: { replaced: false } } })

    await enrol(e, 'BFFcPW6545a5BNP-yn9U_c0MwemXvzddylFa0KbDtANfRTa-OlDzGPv5pUdZAqIhUCvvDVfgjFOyzApW8X2fk1Q', 'my phone')

    expect(asked).toBe(1)
    // `userVisibleOnly: true` is mandatory: Chrome and Edge reject a subscribe
    // without it and Safari revokes permission for an invisible push.
    expect(manager.calls[0].userVisibleOnly).toBe(true)
    expect(manager.calls[0].applicationServerKey).toBeInstanceOf(Uint8Array)
    expect(manager.calls[0].applicationServerKey.length).toBe(65)

    expect(log.calls).toHaveLength(1)
    expect(log.calls[0].path).toBe('/api/push/subscriptions')
    expect(log.calls[0].body).toEqual({
      endpoint: 'https://web.push.apple.com/abc',
      keys: { p256dh: 'BPUB', auth: 'AUTH' },
      origin: 'https://sinet.example.ts.net',
      label: 'my phone',
    })
  })

  test('a refused permission enrols nothing and says so', async () => {
    const e = env({ windowPushManager: fakeManager(), requestPermission: async () => 'denied' })
    const log = scriptedFetch({})
    await expect(enrol(e, 'BPUB', '')).rejects.toThrow(/not allowed/)
    expect(log.calls).toHaveLength(0)
  })

  test('an already-granted permission is not re-asked', async () => {
    const manager = fakeManager()
    let asked = 0
    const e = env({
      windowPushManager: manager,
      permission: 'granted',
      requestPermission: async () => {
        asked++
        return 'granted'
      },
    })
    scriptedFetch({ 'POST /api/push/subscriptions': { body: { replaced: false } } })
    await enrol(e, 'BPUB', '')
    expect(asked).toBe(0)
  })

  test('the classic path registers the push-only worker at the root scope', async () => {
    const container = fakeContainer()
    const e = env({ serviceWorker: container, permission: 'granted' })
    scriptedFetch({ 'POST /api/push/subscriptions': { body: { replaced: false } } })
    await enrol(e, 'BPUB', '')
    expect(container.registered).toEqual([swPath])
  })

  test('unenrolling tells the platform BEFORE it forgets the subscription', async () => {
    const held = fakeSubscription('https://web.push.apple.com/leaving')
    const manager = fakeManager(held)
    const log = scriptedFetch({ 'POST /api/push/subscriptions/remove': { body: { applied: true } } })
    await unenrol(env({ windowPushManager: manager, permission: 'granted' }))
    // The order is the point: a browser that forgot first would leave a row
    // this page can never clean up again.
    expect(log.calls[0].body).toEqual({ endpoint: 'https://web.push.apple.com/leaving' })
    expect(held.unsubscribed).toBe(true)
  })
})

test('the VAPID key comes from the served read, never from a constant', () => {
  const served = (pushView().vapid_public_key as string) ?? ''
  expect(served.length).toBeGreaterThan(80)
  const bytes = decodeVAPIDKey(served)
  expect(bytes.length).toBe(65)
  expect(bytes[0]).toBe(0x04)
  // The negative: no source file under web/src carries a key literal.
  const sources = import.meta.glob('./**/*.{ts,tsx}', { query: '?raw', import: 'default', eager: true }) as Record<
    string,
    string
  >
  const hits = Object.entries(sources)
    .filter(([p]) => !p.endsWith('push.test.tsx'))
    .filter(([, text]) => text.includes(served))
    .map(([p]) => p)
  expect(hits, 'the served application server key is hard-coded somewhere in web/src').toEqual([])
})

test('enrolmentBody refuses a subscription with no key material', () => {
  const broken: PushSubscriptionLike = {
    endpoint: 'https://push.example/x',
    toJSON: () => ({ endpoint: 'https://push.example/x' }),
    unsubscribe: async () => true,
  }
  expect(enrolmentBody(broken, 'https://sinet.example.ts.net', '')).toBeNull()
})

// ── the panel ──────────────────────────────────────────────────────────────

function panelRoutes(view: Record<string, unknown> = pushView()) {
  return {
    'GET /api/auth/session': signedIn,
    'GET /api/push/subscriptions': { body: view },
  }
}

describe('the “This device” panel', () => {
  beforeEach(() => {
    FakeSource.reset()
  })
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  const stream = () => new EventStream({ createEventSource: (url) => new FakeSource(url) })

  test('renders the served device list as METADATA and never an endpoint', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    const text = ui.container.textContent ?? ''
    expect(text).toContain('Alice’s phone')
    expect(text).toContain('Op’s laptop')
    expect(text).toContain('every device enrolled in this household')
    // The whole rendered DOM carries no endpoint. It WALKS the tree rather than
    // serializing it: serializing would put a token this tree's own escape scan
    // forbids into this file (the §43 precedent).
    expect(renderedStrings(ui.container).filter((v) => v.includes('push.apple.com') || v.includes('googleapis'))).toEqual([])
    // The control: the walk really does see the rendered values, so "no hits"
    // means "nothing leaked" rather than "the walk read nothing".
    expect(renderedStrings(ui.container).some((v) => v.includes('Alice’s phone'))).toBe(true)
    ui.unmount()
  })

  test('a member’s body is a NARROWER reading and says which one it is', async () => {
    scriptedFetch(panelRoutes(pushViewMember()))
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    const text = ui.container.textContent ?? ''
    expect(text).toContain('your own enrolled devices')
    expect(text).not.toContain('Op’s laptop')
    ui.unmount()
  })

  test('states what leaves this machine, from the SERVER’s own sentence', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ windowPushManager: fakeManager() })} />)
    await flush()
    expect(ui.container.textContent).toContain(pushView().observable as string)
    ui.unmount()
  })

  test('NOTHING asks for permission on mount', async () => {
    let asked = 0
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices
        stream={stream()}
        env={env({
          windowPushManager: fakeManager(),
          requestPermission: async () => {
            asked++
            return 'granted'
          },
        })}
      />,
    )
    await flush()
    expect(asked, 'a permission prompt fired on mount, outside any user gesture').toBe(0)
    ui.unmount()
  })

  test('an unsupported browser renders its reason and offers no control', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(<PushDevices stream={stream()} env={env({ hasPushManager: false })} />)
    await flush()
    expect(ui.container.querySelector('[data-push-state="unsupported"]')?.textContent).toContain('Add to Home Screen')
    expect(ui.container.querySelector('.push-device button')).toBeNull()
    ui.unmount()
  })

  test('a blocked browser says the browser will not let us ask again', async () => {
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices stream={stream()} env={env({ windowPushManager: fakeManager(), permission: 'denied' })} />,
    )
    await flush()
    expect(ui.container.querySelector('[data-push-state="denied"]')?.textContent).toContain('blocked')
    ui.unmount()
  })

  test('a subscription the platform does not list is stated, not glossed', async () => {
    // The browser holds one; the served list carries a DIFFERENT hash. Saying
    // "enrolled" would be false and saying "not enrolled" would be worse.
    scriptedFetch(panelRoutes())
    const ui = mount(
      <PushDevices
        stream={stream()}
        env={env({ windowPushManager: fakeManager(fakeSubscription('https://web.push.apple.com/unknown-one')), permission: 'granted' })}
      />,
    )
    await flush()
    await flush()
    await flush()
    expect(ui.container.querySelector('[data-push-state="unknown-subscription"]')).not.toBeNull()
    // The control: the SAME world with the endpoint the served list DOES carry
    // renders enrolled, so this is about the mismatch and not about a branch
    // that always fires.
    expect(ui.container.textContent).toContain('does not have on file')
    ui.unmount()
  })

})

/** renderedStrings collects every text node and every attribute value under a
 *  node — the whole rendered surface, without serializing it to markup. */
function renderedStrings(root: Element): string[] {
  const out: string[] = []
  const walk = (el: Element) => {
    for (const attr of Array.from(el.attributes)) out.push(attr.value)
    for (const child of Array.from(el.childNodes)) {
      if (child.nodeType === 3) out.push(child.textContent ?? '')
      else if (child.nodeType === 1) walk(child as Element)
    }
  }
  walk(root)
  return out
}
